# Generated by Django 4.2.4 on 2024-03-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('herbs', models.TextField(max_length=300)),
                ('energies', models.CharField(max_length=100)),
            ],
        ),
    ]
