# Generated by Django 4.2.4 on 2024-03-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_planets_planet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='energies',
            field=models.CharField(max_length=250),
        ),
    ]
