# Generated by Django 4.2.4 on 2024-03-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Herb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('recipe_name', models.CharField(max_length=50)),
                ('planets', models.ManyToManyField(to='main_app.planet')),
            ],
        ),
    ]
