# Generated by Django 4.2.4 on 2024-03-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_herb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredients',
            new_name='other_ingredients',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='herbs',
        ),
        migrations.AlterField(
            model_name='herb',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='herb',
            name='planets',
            field=models.ManyToManyField(related_name='herbs', to='main_app.planet'),
        ),
        migrations.RemoveField(
            model_name='herb',
            name='recipe_name',
        ),
        migrations.AddField(
            model_name='herb',
            name='recipe_name',
            field=models.ManyToManyField(related_name='herbs', to='main_app.recipe'),
        ),
    ]
